### ISSUE TITLE
issue_in_other_org

### ISSUE THREAD

**Issue by Chu127001** [ChuQATestOrganization-123/literate-octo-system.literate-octo-system.#1]
issue_in_other_org

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Contract address: [0x71dfb4ccf7848e19549adeef569e2ad46e24221c](https://ropsten.etherscan.io/address/0x71dfb4ccf7848e19549adeef569e2ad46e24221c)
Network: Testnet (Ropsten)
Paid to: churik
Visit [https://testing.openbounty.status.im](https://testing.openbounty.status.im) to learn more.
